<button type="button" class="btn btn-primary" onclick="location.reload()">Refresh Data</button>

<table id="gitapi" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th class="th-sm">Name
        </th>
        <th class="th-sm">Created Date
        </th>
        <th class="th-sm">Last Push Date
        </th>
        <th class="th-sm">Description
        </th>
        <th class="th-sm">Number Of Stars
        </th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($results as $result):?>
    <tr>
        <td>
            <a href="<?=$result['url']?>"><?=$result['full_name']?></a>
        </td>
        <td>
            <?=$result['created_date']?>
        </td>
        <td>
            <?=$result['last_push_date']?>
        </td>
        <td>
            <?=$result['project_description']?>
        </td>
        <td>
            <?=$result['number_of_stars']?>
        </td>
    </tr>
    <?php endforeach;?>
    </tbody>
</table>
<script>
$(document).ready(function () {
//Pagination numbers
$('#gitapi').DataTable({
"pagingType": "simple_numbers"
});
});

</script>