<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework Installed and Modified by Idowu Davis</span></h1>

    <p>
        <a href="<?=$this->url('application:api')?>" target="_blank">ZF Github Api Application</a>.
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/adejumo23/githubapi.git">Idowu's Zend Framework on GitHub &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Discover Modules</h2>
            </div>
            <div class="card-body">
                <p>
                    This will lead you
                    To a list of the most
                    Starred PHP projects
                    Github
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('application:api')?>">Explore Github's Most starred List</a></p>
            </div>
        </div>
    </div>

<!--    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Help &amp; Support</h2>
            </div>
            <div class="card-body">
                <p>
                    If you need any help or support while developing with ZF,
                    you may reach us via IRC: <a href="irc://irc.freenode.net/zftalk">#zftalk on Freenode</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding this release. Alternatively, you may subscribe
                    and post questions to the <a href="http://framework.zend.com/archives/">mailing lists</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Ping us on IRC &raquo;</a></p>
            </div>
        </div>
    </div>-->
</div>
